<a href="https://colab.research.google.com/github/salmakhale/ML-Data-Analysis/blob/main/04_Python_for_Data_Analysis_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

# Series
you can convert list, numpy, or dictionary to a Series

In [ ]:
#create Series
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])

In [ ]:
#Show first three rows
ser1.head(3)

USA        1
Germany    2
USSR       3
dtype: int64

# DataFrames

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [ ]:
X=np.random.randn(5,4)
X

array([[-0.1665268 , -0.72884615,  0.59388795,  0.90865226],
       [-1.90116764, -0.76767197,  0.33463186, -1.4827183 ],
       [ 0.22293974, -1.83727636,  0.78183578,  1.07025699],
       [-0.55405846, -0.93499735,  0.72323649, -0.36778384],
       [-0.66309567, -0.1275248 , -0.45188099,  0.54747266]])

In [ ]:
index=['A','B','C','D','E']
index

['A', 'B', 'C', 'D', 'E']

In [ ]:
columns=['W','X','Y','Z']
columns

['W', 'X', 'Y', 'Z']

In [ ]:
#create DataFrame
df = pd.DataFrame(data=X,index=index,columns=columns)

df.head()

          W         X         Y         Z
A -0.166527 -0.728846  0.593888  0.908652
B -1.901168 -0.767672  0.334632 -1.482718
C  0.222940 -1.837276  0.781836  1.070257
D -0.554058 -0.934997  0.723236 -0.367784
E -0.663096 -0.127525 -0.451881  0.547473

# Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [ ]:
df['W']

A   -0.166527
B   -1.901168
C    0.222940
D   -0.554058
E   -0.663096
Name: W, dtype: float64

In [ ]:
# Pass a list of column names
df[['W','Z']]

          W         Z
A -0.166527  0.908652
B -1.901168 -1.482718
C  0.222940  1.070257
D -0.554058 -0.367784
E -0.663096  0.547473

### Creating a new column:

In [ ]:
df['new'] = df['W'] + df['Y']

df.head()

          W         X         Y         Z       new
A -0.166527 -0.728846  0.593888  0.908652  0.427361
B -1.901168 -0.767672  0.334632 -1.482718 -1.566536
C  0.222940 -1.837276  0.781836  1.070257  1.004776
D -0.554058 -0.934997  0.723236 -0.367784  0.169178
E -0.663096 -0.127525 -0.451881  0.547473 -1.114977

### Removing Columns

In [ ]:
df.drop('new',axis=1)

          W         X         Y         Z
A -0.166527 -0.728846  0.593888  0.908652
B -1.901168 -0.767672  0.334632 -1.482718
C  0.222940 -1.837276  0.781836  1.070257
D -0.554058 -0.934997  0.723236 -0.367784
E -0.663096 -0.127525 -0.451881  0.547473

In [ ]:
# Not inplace unless specified!
df

          W         X         Y         Z       new
A -0.166527 -0.728846  0.593888  0.908652  0.427361
B -1.901168 -0.767672  0.334632 -1.482718 -1.566536
C  0.222940 -1.837276  0.781836  1.070257  1.004776
D -0.554058 -0.934997  0.723236 -0.367784  0.169178
E -0.663096 -0.127525 -0.451881  0.547473 -1.114977

In [ ]:
df.drop('new',axis=1,inplace=True)

In [ ]:
df

          W         X         Y         Z
A -0.166527 -0.728846  0.593888  0.908652
B -1.901168 -0.767672  0.334632 -1.482718
C  0.222940 -1.837276  0.781836  1.070257
D -0.554058 -0.934997  0.723236 -0.367784
E -0.663096 -0.127525 -0.451881  0.547473

Can also drop rows this way:

In [ ]:
df.drop('E',axis=0)

          W         X         Y         Z
A -0.166527 -0.728846  0.593888  0.908652
B -1.901168 -0.767672  0.334632 -1.482718
C  0.222940 -1.837276  0.781836  1.070257
D -0.554058 -0.934997  0.723236 -0.367784

### Selecting Rows

In [ ]:
#Row of A
df.loc['A']

W   -0.166527
X   -0.728846
Y    0.593888
Z    0.908652
Name: A, dtype: float64

##### Or select based off of position instead of label

In [ ]:
#Row of index two (الصف الثالث)
df.iloc[2]

W    0.222940
X   -1.837276
Y    0.781836
Z    1.070257
Name: C, dtype: float64

In [ ]:
df.iloc[:2,:1]

          W
A -0.166527
B -1.901168

### Selecting subset of rows and columns

In [ ]:
df.loc['B','Y']

0.33463185901936837

In [ ]:
df.loc[['A','B'],['W','Y']]

          W         Y
A -0.166527  0.593888
B -1.901168  0.334632

# Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [ ]:
df

          W         X         Y         Z
A -0.166527 -0.728846  0.593888  0.908652
B -1.901168 -0.767672  0.334632 -1.482718
C  0.222940 -1.837276  0.781836  1.070257
D -0.554058 -0.934997  0.723236 -0.367784
E -0.663096 -0.127525 -0.451881  0.547473

In [ ]:
df>0

       W      X      Y      Z
A  False  False   True   True
B  False  False   True  False
C   True  False   True   True
D  False  False   True  False
E  False  False  False   True

In [ ]:
df[df>0]

         W   X         Y         Z
A      NaN NaN  0.593888  0.908652
B      NaN NaN  0.334632       NaN
C  0.22294 NaN  0.781836  1.070257
D      NaN NaN  0.723236       NaN
E      NaN NaN       NaN  0.547473

In [ ]:
df[df['W']>0]

         W         X         Y         Z
C  0.22294 -1.837276  0.781836  1.070257

In [ ]:
df[df['W']>0]['Y']

C    0.781836
Name: Y, dtype: float64

### For two conditions you can use | and & with parenthesis:

In [ ]:
df[(df['W']>0) & (df['Y'] < 1)]

         W         X         Y         Z
C  0.22294 -1.837276  0.781836  1.070257

# More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [ ]:
newind = ['CA', 'NY', 'WY', 'OR', 'CO']
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [ ]:
df['States'] = newind
df

          W         X         Y         Z States
A -0.166527 -0.728846  0.593888  0.908652     CA
B -1.901168 -0.767672  0.334632 -1.482718     NY
C  0.222940 -1.837276  0.781836  1.070257     WY
D -0.554058 -0.934997  0.723236 -0.367784     OR
E -0.663096 -0.127525 -0.451881  0.547473     CO

In [ ]:
#Set index
df.set_index('States',inplace=True)
df

               W         X         Y         Z
States
CA     -0.166527 -0.728846  0.593888  0.908652
NY     -1.901168 -0.767672  0.334632 -1.482718
WY      0.222940 -1.837276  0.781836  1.070257
OR     -0.554058 -0.934997  0.723236 -0.367784
CO     -0.663096 -0.127525 -0.451881  0.547473

# Missing Data

Let's show a few convenient methods to deal with Missing Data in pandas:

In [ ]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.isna()

       A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

In [ ]:
df.isna().sum()

A    1
B    2
C    0
dtype: int64

In [ ]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [ ]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.dropna() #inplace=True

     A    B  C
0  1.0  5.0  1

In [ ]:
df.reset_index(drop=True,inplace=True)

In [ ]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [ ]:
df.fillna(value='FILL VALUE')

            A           B  C
0         1.0         5.0  1
1         2.0  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [ ]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

# duplicated

Let's show a few convenient methods to deal with duplicated Data in pandas:

In [ ]:
df = pd.DataFrame({'A':[1,1,15,1],
                  'B':[2,2,11,2],
                  'C':[3,3,7,2],
                  'C':[3,3,7,3]})

df

    A   B  C
0   1   2  3
1   1   2  3
2  15  11  7
3   1   2  3

In [ ]:
df.duplicated()

0    False
1     True
2    False
3     True
dtype: bool

In [ ]:
df.duplicated().sum()

2

In [ ]:
df.drop_duplicates()

    A   B  C
0   1   2  3
2  15  11  7

# Operations

There are lots of operations with pandas that will be really useful to you, but don't fall into any distinct category. Let's show them here in this lecture:

In [ ]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],
                   'col2':[444,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

### Info on Unique Values

In [ ]:
df['col2'].unique()

array([444, 555, 666], dtype=int64)

In [ ]:
df['col2'].nunique()

3

In [ ]:
df['col2'].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [ ]:
df['col2'].value_counts().sort_values()

col2
555    1
666    1
444    2
Name: count, dtype: int64

# Applying Functions

In [ ]:
def times2(x):
    return x*2

In [ ]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [ ]:
df['col1'].apply(lambda x:x*2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

### Get column and index names:

In [ ]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      int64
 1   col2    4 non-null      int64
 2   col3    4 non-null      object
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [ ]:
df.describe()

           col1        col2
count  4.000000    4.000000
mean   2.500000  527.250000
std    1.290994  106.274409
min    1.000000  444.000000
25%    1.750000  444.000000
50%    2.500000  499.500000
75%    3.250000  582.750000
max    4.000000  666.000000

### Groupby

The groupby method allows you to group rows of data together and call aggregate functions

In [ ]:
import pandas as pd

# Create the DataFrame
data = {'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
        'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
        'Sales': [200, 120, 340, 124, 243, 350]}

df = pd.DataFrame(data)

df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

#### Example 1: Group by Company and Calculate Sum of Sales
You can use the groupby() function along with an aggregation function like sum() to group the data by company and calculate the total sales for each company.

In [ ]:
# Group by 'Company' and sum the sales
company_sales_sum = df.groupby('Company').sum()
print(company_sales_sum)

             Person  Sales
Company
FB        CarlSarah    593
GOOG     SamCharlie    320
MSFT     AmyVanessa    464

#### Example 2: Group by Company and Calculate Mean of Sales
You can also calculate the average sales for each company.

In [ ]:
# Group by 'Company' and calculate mean sales
company_sales_mean = df.groupby('Company')['Sales'].mean()
print(company_sales_mean)

Company
FB      296.5
GOOG    160.0
MSFT    232.0
Name: Sales, dtype: float64

#### Example 3: Group by Company and Get Count of Entries
If you want to count how many entries (i.e., how many people) are there for each company, you can use the count() function.

In [ ]:
# Group by 'Company' and count the number of entries
company_sales_count = df.groupby('Company').count()
print(company_sales_count)

         Person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          2      2

#### Example 4: Group by Company and Get Maximum Sales
You can also use the max() function to get the maximum sales for each company.

In [ ]:
# Group by 'Company' and find the maximum sales value
company_sales_max = df.groupby('Company').max()
print(company_sales_max)

          Person  Sales
Company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

#### Example 5: Group by Company and Apply Multiple Aggregation Functions
You can apply multiple aggregation functions at once using the agg() function.

In [ ]:
# Group by 'Company' and apply multiple aggregation functions only to the 'Sales' column
company_sales_agg = df.groupby('Company')['Sales'].agg(['sum', 'mean', 'max'])
print(company_sales_agg)

         sum   mean  max
Company
FB       593  296.5  350
GOOG     320  160.0  200
MSFT     464  232.0  340

In [ ]:
df.groupby('Company').describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [ ]:
df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [ ]:
df.groupby('Company').describe().transpose()['GOOG']

Sales  count      2.000000
       mean     160.000000
       std       56.568542
       min      120.000000
       25%      140.000000
       50%      160.000000
       75%      180.000000
       max      200.000000
Name: GOOG, dtype: float64

#### Concatenation

Concatenation basically glues together DataFrames. Keep in mind that dimensions should match along the axis you are concatenating on. You can use **pd.concat** and pass in a list of DataFrames to concatenate together:

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [ ]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7])

In [ ]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [ ]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [ ]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [ ]:
pd.concat([df1,df2,df3])

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [ ]:
pd.concat([df1,df2,df3],axis=1)

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

# Read and Save data

This notebook is the reference code for getting Read and Save, pandas can read a variety of file types using its pd.read_ methods. Let's take a look at the most common data types:

In [ ]:
df = pd.read_csv('data.csv')
df.head()

   rank         state state_code  2020_census  percent_of_total
0     1    California         CA   39538223.0            0.1191
1     2         Texas         TX   29145505.0            0.0874
2     3       Florida         FL   21538187.0            0.0647
3     4           NaN         NY          NaN            0.0586
4     5  Pennsylvania         PA   13002700.0            0.0386

In [ ]:
df = pd.read_csv('data.csv',sep=',')  #delimiter but dose n`t have default value
df.head()

   rank         state state_code  2020_census  percent_of_total
0     1    California         CA   39538223.0            0.1191
1     2         Texas         TX   29145505.0            0.0874
2     3       Florida         FL   21538187.0            0.0647
3     4           NaN         NY          NaN            0.0586
4     5  Pennsylvania         PA   13002700.0            0.0386

In [ ]:
df = pd.read_csv('data.csv',na_values='CA')
df.head()

   rank         state state_code  2020_census  percent_of_total
0     1    California        NaN   39538223.0            0.1191
1     2         Texas         TX   29145505.0            0.0874
2     3       Florida         FL   21538187.0            0.0647
3     4           NaN         NY          NaN            0.0586
4     5  Pennsylvania         PA   13002700.0            0.0386

In [ ]:
df = pd.read_csv('data.csv',index_col=['rank'])
df.head()

             state state_code  2020_census  percent_of_total
rank
1       California         CA   39538223.0            0.1191
2            Texas         TX   29145505.0            0.0874
3          Florida         FL   21538187.0            0.0647
4              NaN         NY          NaN            0.0586
5     Pennsylvania         PA   13002700.0            0.0386

In [ ]:
df = pd.read_csv('data.csv',index_col=['rank'],header=0)
df.head()

             state state_code  2020_census  percent_of_total
rank
1       California         CA   39538223.0            0.1191
2            Texas         TX   29145505.0            0.0874
3          Florida         FL   21538187.0            0.0647
4              NaN         NY          NaN            0.0586
5     Pennsylvania         PA   13002700.0            0.0386

In [ ]:
df = pd.read_csv('data.csv',header=0,names=['rank','St','St_co','2020_cen','Per_o_to'])
df.head()

   rank            St St_co    2020_cen  Per_o_to
0     1    California    CA  39538223.0    0.1191
1     2         Texas    TX  29145505.0    0.0874
2     3       Florida    FL  21538187.0    0.0647
3     4           NaN    NY         NaN    0.0586
4     5  Pennsylvania    PA  13002700.0    0.0386

In [ ]:
df = pd.read_csv('data.csv',nrows=3)
df.head()

   rank       state state_code  2020_census  percent_of_total
0     1  California         CA     39538223            0.1191
1     2       Texas         TX     29145505            0.0874
2     3     Florida         FL     21538187            0.0647

In [ ]:
df = pd.read_csv('data.csv',skiprows=3)
df.head()

   3       Florida  FL    21538187  0.0647
0  4           NaN  NY         NaN  0.0586
1  5  Pennsylvania  PA  13002700.0  0.0386
2  6           NaN  IL         NaN  0.0382
3  7          Ohio  OH  11799448.0     NaN
4  8       Georgia  GA  10711908.0  0.0320

# Saving Csv

In [ ]:
df = pd.read_csv('data.csv')
df.to_csv('output.csv',index=False)