<a href="https://colab.research.google.com/github/salmakhale/ML-Data-Analysis/blob/main/Statistics%2C_Math_In_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Statistics

In [ ]:
import numpy as np

In [ ]:
data = [10, 10, 30, 40, 50, 60, 70, 80, 90, 100]
# mean

In [ ]:
mean=np.mean(data)
print(mean)

55.0

In [ ]:
median=np.median(data)
print(median)

55.0

In [ ]:
from scipy import stats
mode = stats.mode(data)
print(mode)

ModeResult(mode=10, count=2)

In [ ]:
# range
range_value= np.ptp(data)
print(range_value)

90

In [ ]:
# variance
variance=np.var(data, ddof=0)
print(variance)

904.0

In [ ]:
# sd
sd=np.std(data,ddof=0)
print(sd)

30.066592756745816

In [ ]:
# Quartile
q=np.quantile(data, [0.25, 0.5, 0.75])
print(q)

[32.5 55.  77.5]

In [ ]:
percentile=np.percentile(data, 25)
print(percentile)

32.5

In [ ]:
percentile=np.percentile(data, 90)
print(percentile)

91.0

## Math

In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3,4]
my_array= np.array(my_list)
print('type of array', type(my_array), "type of list",type(my_list) )

type of array <class 'numpy.ndarray'> type of list <class 'list'>

In [ ]:
print("Dimensions of my_array", my_array.ndim)

Dimensions of my_array 1

In [ ]:
my_array.shape

(4,)

In [ ]:
my_array.dtype

dtype('int64')

array of zeros

In [ ]:
z=np.zeros((3,2))
z

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
one=np.ones((3,2))
one

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
x=np.diag([20,30,40])
x

array([[20,  0,  0],
       [ 0, 30,  0],
       [ 0,  0, 40]])

In [ ]:
x=np.full((2,3), 7)
x

array([[7, 7, 7],
       [7, 7, 7]])

In [ ]:
x= np.eye(4)
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Transpose

In [ ]:
x= np.array([
    [1,2,3],
    [4,5,6],
    [2,4,6]])
print(x.T)

[[1 4 2]
 [2 5 4]
 [3 6 6]]

In [ ]:
x=x.flatten()
x

array([1, 2, 3, 4, 5, 6, 2, 4, 6])

In [ ]:
x=np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
x[1:3,:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
x[1:3,2:4]

array([[ 7,  8],
       [12, 13]])

In [ ]:
x= np.array([
    [1,2,3],
    [4,5,6]])
y= np.array([
    [1,2,3],
    [4,5,6]])

In [ ]:
#element wise operation
x/y

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x.sum()
x.sum(axis=0)

array([5, 7, 9])

In [ ]:
x.shape

(2, 3)

In [ ]:
x= np.array([
    [1,2,3],
    [4,5,6]])
y= np.array([
    [1,2,3],
    [4,5,6]])

In [ ]:
# default keepdims = False
x=x.sum(axis=1)
print(x, x.shape)

[ 6 15] (2,)

In [ ]:
y=y.sum(axis=1,keepdims=True)
print(y, y.shape)

[[ 6]
 [15]] (2, 1)

In [ ]:
print(x.sum(axis=1,keepdims=False))
print(x.sum(axis=1,keepdims=True)) #keep dimension 2-d

[ 6 15]

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.exp(x)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [ ]:
y=np.log(x)
y

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [ ]:
y=np.log2(x)
y

array([[0.        , 1.        , 1.5849625 ],
       [2.        , 2.32192809, 2.5849625 ]])

Reshape

In [ ]:
x= np.array([
    [10,20,30,40],
    [4,5,6,7],
    [2,2,1,0]])
x.shape

(3, 4)

In [ ]:
x.reshape(2,6)

array([[10, 20, 30, 40,  4,  5],
       [ 6,  7,  2,  2,  1,  0]])

In [ ]:
x.reshape(2,-1)

array([[10, 20, 30, 40,  4,  5],
       [ 6,  7,  2,  2,  1,  0]])

In [ ]:
print(x.reshape(-1,3))
print( x.shape)

[[10 20 30]
 [40  4  5]
 [ 6  7  2]
 [ 2  1  0]]
(3, 4)

In [ ]:
x

array([[10, 20, 30, 40],
       [ 4,  5,  6,  7],
       [ 2,  2,  1,  0]])

In [ ]:
y= np.array([
    [10,20,30,40],
    [4,5,6,7],
    [2,2,1,0]])

x=y.reshape(-1,2)
print(x)
print(x.shape)

[[10 20]
 [30 40]
 [ 4  5]
 [ 6  7]
 [ 2  2]
 [ 1  0]]
(6, 2)

In [ ]:
y= np.array([
    [10,20,30,40],
    [4,5,6,7],
    [2,2,1,0]])

x=y.reshape(1,-1)
print(x)
print(x.shape)

[[10 20 30 40  4  5  6  7  2  2  1  0]]
(1, 12)

In [ ]:
y= np.array([
    [10,20,30,40],
    [4,5,6,7],
    [2,2,1,0]])

x=y.reshape(-1,1)
print(x)
print(x.shape)

[[10]
 [20]
 [30]
 [40]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 2]
 [ 2]
 [ 1]
 [ 0]]
(12, 1)

In [ ]:
y= np.array([
    [10,20,30,40],
    [4,5,6,7],
    [2,2,1,0]])

x=y.reshape(-1)
print(x)
print(x.shape)

[10 20 30 40  4  5  6  7  2  2  1  0]
(12,)

In [ ]:
y= np.array([
    [10,20,30,40],
    [4,5,6,7],
    [2,2,1,0]])

x=y.flatten()
print(x)
print(x.shape)

[10 20 30 40  4  5  6  7  2  2  1  0]
(12,)

#Pandas

In [ ]:
# series
# data frame

#### Running pandas

In [ ]:
import pandas as pd

In [ ]:
pd.__version__

'2.1.4'

#### Introduction to pandas Series

In [ ]:
# seris from a list
# np.nan: Not a Number
# NaN (not a number) is the standard missing data marker used in pandas
s = pd.Series([1,3,5,np.nan,6,8])
print(s)

0    1.0
1    2.0
2    3.0
3    NaN
4    5.0
dtype: float64

In [ ]:
import pandas as pd
product= ['A','B','C','D']
Seris_product=pd.Series(product)
Seris_product

0    A
1    B
2    C
3    D
dtype: object

In [ ]:
type(product)

list

In [ ]:
type(Seris_product)

pandas.core.series.Series

In [ ]:
Seris_product

0    A
1    B
2    C
3    D
dtype: object

In [ ]:
print(Seris_product.name)
Seris_product.name='Product_Cate'
print(Seris_product.name)

None
Product_Cate

In [ ]:
Seris_product[3] #D

'D'

In [ ]:
# Putting A custom indices
list1=['e','s','h']
labels = [1,2,3]
s=pd.Series(data=labels, index=list1)
s

e    1
s    2
h    3
dtype: int64

In [ ]:
# pd.Series(data = list1 , index=labels)
# pd.Series(labels)
# pd.Series(data= [sum,len])
# pd.Series([1,2,3], index=['e','ds','s'])

In [ ]:
# pd.Series(data= [sum(labels)])

In [ ]:
s[1]

<ipython-input-114-f8bb2b116405>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[1]

2

In [ ]:
# putt custom index
list2=[1,2,3]
labels = [10,60,30]
s=pd.Series(labels, list2)
s

1    10
2    60
3    30
dtype: int64

In [ ]:
s[2]

60

In [ ]:
# series from function
# putt custom index
labels = [10,60,30]
pd.Series(sum(labels),['a'])

a    100
dtype: int64

In [ ]:
#create a Series from an array
data = np.array(['a', 'b', 'c', 'd'])
s = pd.Series(data, index=[100, 101, 102, 103])
s.index

Index([100, 101, 102, 103], dtype='int64')

In [ ]:
# create a Series from a dict
data1 = {'a' : 0., 'b' : 1., 'c' : 2.}
s = pd.Series(data1)
s

a    0.0
b    1.0
c    2.0
dtype: float64

In [ ]:
data1 = {'a' : 0, 'b' : 1, 'c' : 2}
# datatype
print(type(data1))

<class 'dict'>

In [ ]:
import pandas as pd
d={'a':10, 'r':10, 'c':34}
# pd.Series(d)
pd.Series(list(d.values()),list(d.keys()))
# pd.Series(list(d.values()),index=list(d.keys()))

0    0
1    1
2    2
dtype: int64

#### Using an Index in pandas

In [ ]:
product= pd.Series({'A':1500,'B':2000,'C':4000,'D':5000})
product

A    1500
B    2000
C    4000
D    5000
dtype: int64

In [ ]:
product.dtype

dtype('int64')

In [ ]:
product.size

In [ ]:
product.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [ ]:
product.values

array([1500, 2000, 4000, 5000])

#### Using Methods in Python - Part I

In [ ]:
import pandas as pd

In [ ]:
start_date_deposits = pd.Series({
    '7/4/2014'   : 2000,
    '1/2/2015'   : 2000,
    '12/8/2012'  : 1000,
    '2/20/2015'  : 2000,
    '10/28/2013' : 2000,
    '4/19/2015'  : 2000,
    '7/4/2016'   : 2000,
    '4/24/2014'  : 2000,
    '9/3/2015'   : 4000,
    '7/25/2016'  : 2000,
    '5/1/2014'   : 2000,
    '3/29/2013'  : 2000,
    '10/3/2014'  : 2000,
    '9/18/2015'  : 2500
})

In [ ]:
start_date_deposits

7/4/2014      2000
1/2/2015      2000
12/8/2012     1000
2/20/2015     2000
10/28/2013    2000
4/19/2015     2000
7/4/2016      2000
4/24/2014     2000
9/3/2015      4000
7/25/2016     2000
5/1/2014      2000
3/29/2013     2000
10/3/2014     2000
9/18/2015     2500
dtype: int64

In [ ]:
start_date_deposits.sum()

29500

In [ ]:
start_date_deposits.min()

1000

In [ ]:
start_date_deposits.max()

4000

In [ ]:
start_date_deposits.head()
# head(10)

7/4/2014      2000
1/2/2015      2000
12/8/2012     1000
2/20/2015     2000
10/28/2013    2000
dtype: int64

In [ ]:
start_date_deposits.tail()

7/25/2016    2000
5/1/2014     2000
3/29/2013    2000
10/3/2014    2000
9/18/2015    2500
dtype: int64

### Creating DataFrames from Scratch

### Creating DataFrames from Scratch

<u>**#1: Construct a DataFrame from a dictionary of lists**</u>

In [ ]:
df=pd.DataFrame(np.random.randn(6,4), columns=['A','B','C','D'])
df
print(df)

          A         B         C         D
0  0.755640 -0.822019  1.326916 -0.130693
1  1.372332 -0.332390 -0.618851 -1.288913
2 -1.198605 -0.284240  0.377234 -0.070810
3 -1.067294 -0.995728  0.179086  0.319093
4  1.581377  1.471981  1.921138 -0.404582
5 -0.412834  0.794909 -1.843150  0.897228

In [ ]:
data = {'ProductName':['Product A', 'Product B', 'Product C'], 'ProductPrice' :[22250, 16600, 12500]}
df = pd.DataFrame(data)
df

In [ ]:
data = {'ProductName':['Product A', 'Product B', 'Product C', 'Product D'], 'ProductPrice':[22250, 16600, 12500]}
#df = pd.DataFrame(data) #error ->All arrays must be of the same length
#df

*italicized text*<u>**#2: Construct a DataFrame from a dictionary of lists + specify an index**</u>

In [ ]:
# dataframe from dict of list
data = {'Productname': ['A','B','C','D'],
        'ProductPrice': [1000,2000,3000,4000]
        }
df= pd.DataFrame(data, index=['a','b','c','d'])
df

  Productname  ProductPrice
a           A          1000
b           B          2000
c           C          3000
d           D          4000

<u>**#3: Construct a DataFrame from a list of dictionaries**<u/>

In [ ]:
# dataframe from list of dics

data = [{'Productname': 'A','ProductPrice': 4000},
        {'Productnam': 'B','ProductPrice': 3000}]
df= pd.DataFrame(data)
df

  Productname  ProductPrice Productnam
0           A          4000        NaN
1         NaN          3000          B

In [ ]:
# dataframe from list of dics

data = [{'Productname': 'A','ProductPrice': 4000},
        {'Productname': 'B','ProductPrice': 3000},
        {'Productsize': 'L'}]
df= pd.DataFrame(data)
df

  Productname  ProductPrice Productsize
0           A        4000.0         NaN
1           B        3000.0         NaN
2         NaN           NaN           L

<u>**#4: Construct a DataFrame from a dictionary of pandas Series**<u/>

In [ ]:
# dataframe from dict of series
product= ['A','B','C','D']
Seris_product=pd.Series(product)
Seris_Price	=pd.Series([1000,2000,3000,4000])

data={'Productname': Seris_product,'ProductPrice': Seris_Price}
df=pd.DataFrame(data)

df

  Productname  ProductPrice
0           A          1000
1           B          2000
2           C          3000
3           D          4000

In [ ]:
# dataframe from dict of series
product= ['A','B','C','D']
Seris_product=pd.Series(product,index=['A','B','C','D'])
Seris_Price	=pd.Series([1000,2000,3000,4000], index =['A','B','C','D'])

data={'Productname': Seris_product,'ProductPrice': Seris_Price}
df=pd.DataFrame(data)

df

  Productname  ProductPrice
A           A          1000
B           B          2000
C           C          3000
D           D          4000

In [ ]:
# dataframe from dict of series
product= ['A','B','C','D']
Seris_product=pd.Series(product,index=['A','E','D','B'])
Seris_Price	=pd.Series([1000,2000,3000,4000], index =['A','B','C','D'])

data={'Productname': Seris_product,'ProductPrice': Seris_Price}
df=pd.DataFrame(data)

df

  Productname  ProductPrice
A           A        1000.0
B           D        2000.0
C         NaN        3000.0
D           C        4000.0
E           B           NaN

<u>**#5: Construct a DataFrame from a list of lists**<u/>

In [ ]:
# dataframe from list of list
data = [['A',1000],  #first column first row
        ['B',2000],
         ['C',3000]]
df= pd.DataFrame(data, index=['a','b','c'])
df
df

   0     1
a  A  1000
b  B  2000
c  C  3000

In [ ]:
data = [['Product A', 22250], ['Product B', 16600], ['Product C', 12500]]
df = pd.DataFrame(data)
df

In [ ]:
df.columns = ['ProductName', 'ProductPrice']
df

In [ ]:
df.index = ['A', 'B', 'C']
df

<u>**#6: Construct a DataFrame in a Professional Way**<u/>

In [ ]:
df = pd.DataFrame(data = [['Product A', 22250],
                          ['Product B', 16600],
                          ['Product C', 12500]],
                  columns = ['ProductName', 'ProductPrice'],
                  index = ['A', 'B', 'C'])
df

In [ ]:
# row, column
df.shape

##### Append 2 data frames

In [ ]:
df3= df1.append(df, ignore_index=True)
df3

AttributeError: 'DataFrame' object has no attribute 'append'

In [ ]:
!pip uninstall pandas

Found existing installation: pandas 1.3.5
Uninstalling pandas-1.3.5:
  Would remove:
    /usr/local/lib/python3.10/dist-packages/pandas-1.3.5.dist-info/*
    /usr/local/lib/python3.10/dist-packages/pandas/*
Proceed (Y/n)?   ERROR: Operation cancelled by user

In [ ]:
!pip install pandas==1.3.5

Requirement already satisfied: pandas==1.3.5 in /usr/local/lib/python3.10/dist-packages (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.10/dist-packages (from pandas==1.3.5) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.10/dist-packages (from pandas==1.3.5) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas==1.3.5) (1.26.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7.3->pandas==1.3.5) (1.16.0)

In [ ]:
import pandas as pd

data1 = [['Product AA', 22250], ['Product B', 16600], ['Product C', 12500, 5000]]
data2 = [['Product A', 22250], ['Product B', 16600], ['Product C', 12500, 5000]]

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)


df3 = df2.append(df1, ignore_index=True)

print(df3)

   A   B
0  1   4
1  2   5
2  3   6
3  7  10
4  8  11
5  9  12

In [ ]:
# another way for merging 2 data frames
df3=pd.concat([df,df1], ignore_index=True)
df3

  Productname  ProductPrice
0           A          1000
1           B          2000
2           C          3000
3           A          1000
4           B          2000
5           C          3000

In [ ]:
#Descriptive Stat.
print(df1.count())
print(df1.mean())
print(df1.std())
print(df1.sum())